# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  ip = "10.11.12.21"
  begin
    require './vagrant_local.rb'
    puts 'Selected LOCAL configuration'
    VagrantLocal::configure config, ip
  rescue LoadError => e
    require './vagrant_base.rb'
    puts 'Selected DEFAULT configuration'
    VagrantBase::configure config, ip
  end
end
